#!/bin/sh -e

# Check environment for needed software.

# https://github.com/diku-dk/futhark
if ! command -v futhark; then
    echo "[ERR]: 'futhark' is not available on this system."
    echo "-----: Can fix by installing futhark."
fi

# https://github.com/pepijndevos/futhark-pycffi/
if ! command -v build_futhark_ffi; then
    echo "[ERR]: 'build_futhark_ffi' is not available on this system."
    echo "-----: CMD: 'pip install futhark-ffi'"
fi

FUTHARK_TARGET="${FUTHARK_TARGET:-c}"

BUILD_DOCS="${BUILD_DOCS:-0}"

case $FUTHARK_TARGET in
cuda)
    for l in cuda cudart; do
        export CFLAGS="$CFLAGS $(pkg-config --cflags $l)"
        export CFLAGS="$CFLAGS $(pkg-config --libs $l)"
    done
    ;;
esac

# TODO: add cleaning step
[ -d output ] && rm -rf output
mkdir output
echo "$FUTHARK_TARGET" >> output/futhark_target
cp src/* output
sh gendocs >output/doc.tex 2>/dev/null
cd output
futhark "$FUTHARK_TARGET" --library fustal.fut
build_futhark_ffi fustal
# Try to build both PDF and HTML versions of the documentation.
if command -v latexmk && [ "$BUILD_DOCS_PDF" = 1 ]; then
    latexmk -pdf doc.tex
fi
if command -v make4ht && [ "$BUILD_DOCS_HTML" = 1 ]; then
    make4ht doc.tex "mathjax"
fi
