#!/usr/bin/Rscript

# simple script to generate bar graphs comparing the performance of R & fustal.

mkbargraph <- function(func_name, fv, rv) {

    fn <- paste0("output/bargraph-", func_name, ".png")
    plot_title <- paste0("Time to run ", func_name, " in seconds (lower is better)")
    labels <- c("FUSTAL", "R")
    colors <- c("red", "blue")

    values <- c(fv, rv)
    valuesM <- matrix(values, nrow=1, ncol=2, byrow=FALSE)
    png(file = fn,
        width = 800,
        height = 500)
    barplot(valuesM,
            main = plot_title,
            names.arg = labels,
            xlab = "Backend",
            ylab = "Time in Seconds",
            col = colors,
            beside = TRUE)
    dev.off()
}

df = data.frame(read.csv("output/test-results.csv"))
df = df[!duplicated(df), ]

for (f in df$func) {
    fv <- df$fustal_time_in_s[df["func"] == f]
    rv <- df$r_time_in_s[df["func"] == f]
    mkbargraph(f, fv, rv)
}
