#!/bin/sh

# simple script to generate bar graphs comparing the performance
# of R & fustal.

# NOTE: Because of the output of 'test' I know that the
# first timing is going to be from fustal and the second
# will be from R.

[ -d output ] || exit 1
rm output/plot-data
echo "fustal,R" >> output/plot-data

backend=$(cat output/futhark_target)

numruns=10

for _ in $(seq 1 $numruns); do
    sh test 2>&1 1> /dev/null |
        awk '/real/ { gsub("s", ""); print $2 }' |
        tr '\n' ',' |
        sed "s/,$/\n/" >> output/plot-data
done

cat << EOF | R --no-save
d = read.csv("output/plot-data")
f_avg <- mean(d\$fustal)
r_avg <- mean(d\$R)

fsd <- sd(d\$fustal)
rsd <- sd(d\$R)
colors <- c("red", "blue")
values <- c(f_avg, r_avg)
fl <- paste0("FUSTAL ($backend backend)\\nsd - ", fsd)
rl <- paste0("R\\nsd - ", rsd)
labels <- c(fl, rl)
valuesM <- matrix(values, nrow=1, ncol=2, byrow=FALSE)

png(file = "bargraph.png",
    width=800,
    height=500)
barplot(valuesM, main = "Time to run './test', average of $numruns",
        names.arg = labels,
        xlab = "Backend",
        ylab = "Time in Seconds",
        col = colors,
        beside = TRUE)
dev.off()
t.test(d\$fustal, d\$R)
EOF
