#!/bin/sh -ex

case "$(uname)" in
    Linux)  host=linux   ext=tar.xz;;
    Darwin) host=macos   ext=tar.xz;;
    MINGW*) host=windows ext=zip;;
esac

FUTHARK_TARBALL="https://github.com/diku-dk/futhark/releases/download/nightly/futhark-nightly-$host-x86_64.$ext"

# Setup futhark
mkdir -p .futhark
if [ -e .futhark ]; then
    cd .futhark
    file="$(basename "$FUTHARK_TARBALL")"
    if ! [ -e "$file" ]; then
        curl -LO "$FUTHARK_TARBALL"
    fi
    case $ext in
        tar.xz) tar xvf "$file";;
        zip)    unzip "$file";;
    esac
    cd "$OLDPWD"
fi

# Setup Python
if ! [ -e .venv ]; then
    if command -v python3; then
        pyexec=python3
    elif command -v python; then
        pyexec=python
    else
        echo "Need a valid python (v3) executable!"
        exit 1
    fi
    $pyexec -m venv .venv
fi
. .venv/bin/activate
pip install -r requirements.txt

# Setup gcc on Windows
case $host in
    windows)
        mkdir -p .w64devkit
        if [ -e .w64devkit ]; then
            cd .w64devkit
            W64DEVKIT_VERSION=1.21.0
            W64DEVKIT_TARBALL="https://github.com/skeeto/w64devkit/releases/download/v${W64DEVKIT_VERSION}/w64devkit-${W64DEVKIT_VERSION}.zip"
            curl -LO "$W64DEVKIT_TARBALL"
            unzip "$(basename "$W64DEVKIT_TARBALL")"
        fi
        ;;
esac

case $host in
    windows) venvdir=.venv/Scripts/ ;;
    *)       venvdir=.venv/bin/ ;;
esac

cat > .env << EOF
export PATH="\$PATH:$PWD/.futhark/futhark-nightly-linux-x86_64/bin/"
if [ -e $PWD/.w64devkit ]; then
    export PATH="\$PATH:$PWD/.w64devkit/w64devkit/bin/"
fi
. ${venvdir}activate
EOF

cat << EOF
[INFO]: To use the installed software, run the following in your shell:

$ . .env

EOF
