#!/bin/sh -ex

case "$(uname)" in
    Linux) host=linux;;
    Darwin) host=macos;;
esac

FUTHARK_TARBALL="https://github.com/diku-dk/futhark/releases/download/nightly/futhark-nightly-$host-x86_64.tar.xz"

# Setup futhark
mkdir -p .futhark
if [ -e .futhark ]; then
    cd .futhark
    file="$(echo "$FUTHARK_TARBALL" | rev | cut -d'/' -f1 | rev)"
    if ! [ -e "$file" ]; then
        curl -LO "$FUTHARK_TARBALL"
    fi
    tar xvf "$file"
    cd "$OLDPWD"
fi

# Setup Python
if ! [ -e .venv ]; then
    python3 -m venv .venv
fi
. .venv/bin/activate
pip install -r requirements.txt

cat > .env << EOF
export PATH="$PWD/.futhark/futhark-nightly-linux-x86_64/bin/:$PATH"
. .venv/bin/activate
EOF

cat << EOF
[INFO]: To use the installed software, run the following in your shell:

$ . .env

EOF
