#!/bin/sh
[ -d output ] || exit 1
pout=output/test-py-output
rout=output/test-R-output
echo "fustal" > "$pout"
echo "R" > "$rout"
PYTHONPATH=$PWD/output ./test.py >> "$pout"
R --no-save < test.R | awk '/^\[1\]/ {print $2 "\n" $3}' | sed "/^$/d" >> "$rout"
paste -d'\n' "$pout" "$rout" | paste - -
