#!/bin/sh
# Ensure we only test if the library has been built.
[ -d output ] || exit 1
pout=output/test-py-output
rout=output/test-R-output
echo "fustal" > "$pout"
echo "R" > "$rout"

# Run our two separate programs.
# Each program outputs a series of numbers for a specific test.
# In the future, this should be made to accomodate having the same test
# appear on different lines, because it currently assumes that each line
# is the same test in both outputs.
PYTHONPATH=$PWD/output ./test.py >> "$pout"
R --no-save < test.R | awk '/^\[1\]/ {print $2 "\n" $3}' | sed "/^$/d" >> "$rout"

# Make sure that each test is ran in both programs.
if ! [ $(wc -l < $rout) = $(wc -l < $pout) ]; then
    echo "$rout & $pout do not have the same number of lines."
    exit 1
fi

# Main testing code below. Check if there are any significant
# differences between the numbers that fustal returns vs R.
e=0.00001
paste -d'\n' "$pout" "$rout" | paste - - |
    awk "/[0-9]/ {d=\$1-\$2; d=d*d; d=sqrt(d); if(d > $e){exit 1}}"
if [ $? -eq 0 ]; then
    echo PASSED
    exit 0
else
    echo FAILED
    exit 1
fi
