name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo apt install wget python3 python3-pip r-base

      - name: Setup Futhark
        run: |
          wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
          tar xf futhark-nightly-linux-x86_64.tar.xz
          cd futhark-nightly-linux-x86_64 && PREFIX="$HOME/.local/" make install
          echo "$HOME/.local/bin/" >> $GITHUB_PATH

      - name: Setup futhark-ffi
        run:
          pip install -r requirements.txt

      - name: Build
        run:
          ./build

      - name: Test
        run:
          ./test

