name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo apt install wget python3 python3-pip r-base

      - name: Setup Futhark
        uses: diku-dk/install-futhark@v1.1.0
        with:
          version: 'nightly'

      - name: Setup futhark-ffi
        run:
          pip install -r requirements.txt

      - name: Build
        run:
          ./build

      - name: Test
        run:
          ./test

