name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v1
      - runs-on: ubuntu-latest
      - run: sudo apt install wget

      - run: |
        wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
        tar xf futhark-nightly-linux-x86_64.tar.xz
        cd futhark-nightly-linux-x86_64 && PREFIX="$HOME/.local/" make install
        echo "$HOME/.local/bin/" >> $GITHUB_PATH

      - run:
        ./build

